# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run security checks
      uses: PyCQA/bandit-action@v1

    - name: Run code linting
      uses: andymckay/pycodestyle-action@0.1.3

  runapp:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run Python App
      run: python main.py
      
    - name: Save Output
      run: echo "${{ steps.run_python_app.outputs.stdout }}" > output.txt

    - uses: actions/upload-artifact@v4
      with:
        name: python-app-artifact
        path: output.txt
